//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.12 at 10:18:33 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.app.t13.org/student", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.t13.app.student;
