//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.11 at 09:37:21 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/student", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.t13.app.student;
